import { Menu } from "./list-menu";

export const MENU_DATA: Menu[] = [
  {
    name:'Ajax',
    url:'ajax',
    icon:'ajax.svg'
  },
  {
    name:'Angular',
    url:'angular',
    icon:'angular.svg'
  },
  {
    name:'Arduino',
    url:'arduino',
    icon:'arduino.svg'
  },
  {
    name:'ASP.NET',
    url:'asp',
    icon:'asp.svg'
  },
  {
    name:'Bootstrap',
    url:'bootstrap',
    icon:'bootstrap.svg'
  },
  {
    name:'C#',
    url:'csharp',
    icon:'csharp.svg'
  },
  {
    name:'CSS',
    url:'css',
    icon:'css.svg'
  },
  {
    name:'DOM',
    url:'dom',
    icon:'dom.svg'
  },
  {
    name:'Firebase',
    url:'firebase',
    icon:'firebase.svg'
  },
  {
    name: 'HTML',
    url:'html',
    icon:'html.svg',
    children: [
      {name: 'Header',url:'#',icon:''},
      {name: 'Body',url:'#',icon:''},
    ]
  },
  {
    name:'Java',
    url:'java',
    icon:'java.svg'
  },
  {
    name:'Javascript',
    url:'javascript',
    icon:'javascript.svg',
    children:[
      {name:'String',url:'string',icon:''}
    ]
  },
  {
    name:'jQuery',
    url:'jquery',
    icon:'jquery.svg'
  },
  {
    name:'JSON',
    url:'json',
    icon:'json.svg'
  },
  {
    name:'MySQL',
    url:'mysql',
    icon:'mysql.svg'
  },
  {
    name:'NodeJS',
    url:'nodejs',
    icon:'nodejs.svg'
  },
  {
    name:'PHP',
    url:'php',
    icon:'php.svg'
  },
  {
    name:'React-Native',
    url:'reactnative',
    icon:'reactnative.svg'
  },
  {
    name:'SCSS',
    url:'scss',
    icon:'scss.svg'
  },
  {
    name:'Selenium',
    url:'selenium',
    icon:'selenium.svg'
  },
  {
    name:'Socket.io',
    url:'socket',
    icon:'socket.svg'
  },
  {
    name:'Swift',
    url:'swift',
    icon:'swift.svg'
  },
  {
    name:'Typescript',
    url:'typescript',
    icon:'typescript.svg'
  },
  {
    name:'XML',
    url:'xml',
    icon:'xml.svg'
  },
];